name: Test GPU

on: [push]

jobs:
  gpu-test:
    runs-on: self-hosted-gpu
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install torch
    - name: Check GPU
      run: |
        python -c "import torch; print(torch.cuda.is_available())"
        nvidia-smi
